server:
  port: 8083
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: search-service
  elasticsearch:
    rest:
      uris: http://192.168.1.150:9200
      username: elasticsearch
  jackson:
    default-property-inclusion: non_null  #配置json处理时忽略null值
  rabbitmq:
    host: 192.168.1.150
    port: 5672
    virtual-host: /leyou
    username: leyou
    password: leyou
    template:
      exchange: LEYOU.ITEM.EXCHANGE
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15